# Generated by Django 5.2.17 on 2026-09-29 16:42

import django.db.models.deletion
import owners.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judgments', '0001_initial'),
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=owners.models._new_code, max_length=6, unique=True, verbose_name='코드')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='발급일')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='사용일')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_codes', to='places.building', verbose_name='건물')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_codes', to='places.place', verbose_name='장소')),
            ],
            options={
                'verbose_name': '인증 코드',
                'verbose_name_plural': '인증 코드',
            },
        ),
        migrations.CreateModel(
            name='OwnerClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OPERATOR', '가게 사장님'), ('BUILDING_OWNER', '건물주')], max_length=20, verbose_name='구분')),
                ('status', models.CharField(choices=[('PENDING', '확인 중'), ('APPROVED', '승인됨'), ('REJECTED', '반려됨')], default='PENDING', max_length=10, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신청일')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리일')),
                ('reject_reason', models.CharField(blank=True, max_length=200, verbose_name='반려 사유')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_claims', to='places.building', verbose_name='건물')),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='owners.claimcode', verbose_name='사용한 코드')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_claims', to='places.place', verbose_name='장소')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='처리자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_claims', to=settings.AUTH_USER_MODEL, verbose_name='신청자')),
            ],
            options={
                'verbose_name': '사장님·건물주 인증',
                'verbose_name_plural': '사장님·건물주 인증',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OwnerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistance_contact', models.CharField(blank=True, help_text='예: 입구 호출벨, 전화 02-000-0000', max_length=100, verbose_name='도움 요청 방법')),
                ('assistance_hours', models.CharField(blank=True, help_text='예: 영업시간 내내, 14~17시 제외', max_length=100, verbose_name='도움 가능 시간')),
                ('alt_entrance', models.CharField(blank=True, help_text='예: 건물 뒤편 주차장 쪽 문은 턱이 없어요', max_length=200, verbose_name='다른 출입구 안내')),
                ('owner_comment', models.CharField(blank=True, max_length=200, verbose_name='사장님 한마디')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_response', to='places.place', verbose_name='장소')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '사장님 한마디',
                'verbose_name_plural': '사장님 한마디',
            },
        ),
        migrations.CreateModel(
            name='PlaceViewStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='조회 수')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_stats', to='places.place', verbose_name='장소')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='judgments.conditionprofile', verbose_name='이동 조건')),
            ],
            options={
                'verbose_name': '조회 수',
                'verbose_name_plural': '조회 수',
            },
        ),
        migrations.CreateModel(
            name='SupportProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='사업명')),
                ('target_desc', models.TextField(verbose_name='지원 대상·내용')),
                ('period', models.CharField(blank=True, max_length=100, verbose_name='신청 기간')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='문의처')),
                ('url', models.URLField(blank=True, verbose_name='안내 링크')),
                ('is_active', models.BooleanField(default=True, verbose_name='안내 중')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='표시 순서')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_programs', to='places.region', verbose_name='지역')),
            ],
            options={
                'verbose_name': '지원사업',
                'verbose_name_plural': '지원사업',
                'ordering': ['order', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitWish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_wishes', to='places.place', verbose_name='장소')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='judgments.conditionprofile', verbose_name='이동 조건')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_wishes', to=settings.AUTH_USER_MODEL, verbose_name='이용자')),
            ],
            options={
                'verbose_name': '가고 싶어요',
                'verbose_name_plural': '가고 싶어요',
            },
        ),
        migrations.AddConstraint(
            model_name='claimcode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('building__isnull', True), ('place__isnull', False)), models.Q(('building__isnull', False), ('place__isnull', True)), _connector='OR'), name='claim_code_for_place_or_building'),
        ),
        migrations.AddConstraint(
            model_name='placeviewstat',
            constraint=models.UniqueConstraint(fields=('place', 'profile', 'date'), name='one_stat_per_place_profile_day'),
        ),
        migrations.AddConstraint(
            model_name='visitwish',
            constraint=models.UniqueConstraint(fields=('user', 'place', 'profile'), name='one_wish_per_user_place_profile'),
        ),
    ]
