# Generated by Django 5.2.17 on 2026-09-29 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='건물 이름')),
                ('address', models.CharField(max_length=200, verbose_name='주소')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='위도')),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='경도')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '건물',
                'verbose_name_plural': '건물',
            },
        ),
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('key', models.SlugField(primary_key=True, serialize=False, verbose_name='키')),
                ('label', models.CharField(max_length=50, verbose_name='이름')),
                ('unit', models.CharField(blank=True, max_length=10, verbose_name='단위')),
                ('scope', models.CharField(choices=[('PLACE', '장소'), ('BUILDING', '건물'), ('ENTRANCE', '출입구')], max_length=10, verbose_name='대상')),
                ('value_type', models.CharField(choices=[('NUMBER', '숫자'), ('BOOL', '예/아니오'), ('CHOICE', '선택'), ('TEXT', '글')], max_length=10, verbose_name='값 종류')),
                ('choices', models.JSONField(blank=True, default=list, help_text='CHOICE일 때만. 예: ["자동문", "여닫이"]', verbose_name='선택지')),
                ('help_text', models.CharField(blank=True, max_length=200, verbose_name='측정·확인 방법')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='표시 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 중')),
            ],
            options={
                'verbose_name': '접근성 필드 정의',
                'verbose_name_plural': '접근성 필드 정의',
                'ordering': ['scope', 'order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='URL·API에 쓰는 영문 코드. 예: wolgye1', max_length=30, unique=True, verbose_name='코드')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('center_lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='지도 중심 위도')),
                ('center_lng', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='지도 중심 경도')),
                ('map_level', models.PositiveSmallIntegerField(default=4, help_text='카카오맵 level (작을수록 확대)', verbose_name='지도 확대 레벨')),
                ('boundary', models.JSONField(blank=True, null=True, verbose_name='경계 (GeoJSON)')),
                ('is_active', models.BooleanField(default=True, verbose_name='서비스 중')),
            ],
            options={
                'verbose_name': '지역',
                'verbose_name_plural': '지역',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('category', models.CharField(choices=[('RESTAURANT', '음식점'), ('CAFE', '카페'), ('STORE', '편의점·마트'), ('PHARMACY', '약국'), ('CLINIC', '병원·의원'), ('PUBLIC', '공공기관'), ('ETC', '기타')], default='ETC', max_length=20, verbose_name='유형')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='주소')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='위도')),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='경도')),
                ('floor', models.SmallIntegerField(default=1, help_text='1 = 1층, -1 = 지하 1층', verbose_name='층')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('is_closed', models.BooleanField(default=False, help_text='가게 정보 삭제 대신 폐업으로 처리 (기획 v2 4.4)', verbose_name='폐업')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='places.building', verbose_name='건물')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', to='places.region', verbose_name='지역')),
            ],
            options={
                'verbose_name': '장소',
                'verbose_name_plural': '장소',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='places.region', verbose_name='지역'),
        ),
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='정문', help_text='예: 정문, 주차장 쪽 문', max_length=50, verbose_name='이름')),
                ('is_main', models.BooleanField(default=True, verbose_name='주 출입구')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrances', to='places.building', verbose_name='건물')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrances', to='places.place', verbose_name='장소')),
            ],
            options={
                'verbose_name': '출입구',
                'verbose_name_plural': '출입구',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('building__isnull', True), ('place__isnull', False)), models.Q(('building__isnull', False), ('place__isnull', True)), _connector='OR'), name='entrance_belongs_to_place_or_building')],
            },
        ),
    ]
