# Generated by Django 5.2.17 on 2026-10-01 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddefinition',
            name='scope',
            field=models.CharField(choices=[('PLACE', '장소'), ('BUILDING', '건물'), ('ENTRANCE', '출입구'), ('FACILITY', '접근 시설')], max_length=10, verbose_name='대상'),
        ),
        migrations.CreateModel(
            name='AccessFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ELEVATOR', '엘리베이터 (E/V)'), ('ESCALATOR', '에스컬레이터 (E/S)'), ('STAIRS', '계단'), ('RAMP', '경사로'), ('TOILET', '장애인 화장실'), ('OTHER', '기타 접근 편의시설')], max_length=20, verbose_name='시설 종류')),
                ('name', models.CharField(max_length=50, verbose_name='시설 이름')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='places.building')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='places.place')),
            ],
            options={
                'verbose_name': '접근 시설',
                'verbose_name_plural': '접근 시설',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('building__isnull', True), ('place__isnull', False)), models.Q(('building__isnull', False), ('place__isnull', True)), _connector='OR'), name='facility_belongs_to_place_or_building')],
            },
        ),
    ]
