# Generated by Django 5.2.17 on 2026-10-01 02:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('REPORT', '제보 결과'), ('OWNER_REQUEST', '사장님·건물주 요청 결과'), ('CLAIM', '인증 결과'), ('WISH', '가고 싶어요 가게 소식')], max_length=20, verbose_name='종류')),
                ('message', models.CharField(max_length=200, verbose_name='내용')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='링크')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='만든 시각')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='읽은 시각')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='받는 사람')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_at'], name='notification_user_unread')],
            },
        ),
    ]
