# Generated by Django 5.2.17 on 2026-09-29 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('TEAM_SURVEY', '팀 답사'), ('USER_REPORT', '이용자 제보'), ('OWNER', '사장님·건물주'), ('AI', 'AI 판별')], max_length=20, verbose_name='출처')),
                ('status', models.CharField(choices=[('PENDING', '확인 중'), ('VERIFIED', '반영됨'), ('REJECTED', '반려')], default='PENDING', max_length=10, verbose_name='상태')),
                ('photo', models.ImageField(blank=True, upload_to='reports/%Y/%m/', verbose_name='사진')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리일')),
                ('reject_reason', models.CharField(blank=True, max_length=200, verbose_name='반려 사유')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='places.building', verbose_name='건물')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('entrance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='places.entrance', verbose_name='출입구')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='places.place', verbose_name='장소')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='처리자')),
            ],
            options={
                'verbose_name': '제보',
                'verbose_name_plural': '제보',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessibilityValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_number', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='숫자 값')),
                ('value_bool', models.BooleanField(blank=True, null=True, verbose_name='예/아니오 값')),
                ('value_text', models.CharField(blank=True, max_length=200, verbose_name='글·선택 값')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='places.fielddefinition', verbose_name='필드')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='reports.report', verbose_name='제보')),
            ],
            options={
                'verbose_name': '접근성 값',
                'verbose_name_plural': '접근성 값',
            },
        ),
        migrations.CreateModel(
            name='ReportConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='reports.report', verbose_name='제보')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='확인한 사람')),
            ],
            options={
                'verbose_name': '제보 확인',
                'verbose_name_plural': '제보 확인',
            },
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('building__isnull', True), ('entrance__isnull', True), ('place__isnull', False)), models.Q(('building__isnull', False), ('entrance__isnull', True), ('place__isnull', True)), models.Q(('building__isnull', True), ('entrance__isnull', False), ('place__isnull', True)), _connector='OR'), name='report_has_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='accessibilityvalue',
            constraint=models.UniqueConstraint(fields=('report', 'field'), name='one_value_per_field_per_report'),
        ),
        migrations.AddConstraint(
            model_name='reportconfirmation',
            constraint=models.UniqueConstraint(fields=('report', 'user'), name='one_confirmation_per_user'),
        ),
    ]
