# Generated by Django 5.2.17 on 2026-09-29 12:21

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def copy_created_at(apps, schema_editor):
    # 이미 있던 제보는 확인 시각을 작성 시각으로 (마이그레이션 실행 시각이 들어가지 않게)
    Report = apps.get_model("reports", "Report")
    Report.objects.update(observed_at=F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='report',
            name='report_has_exactly_one_target',
        ),
        migrations.AddField(
            model_name='report',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='제보 위치 위도'),
        ),
        migrations.AddField(
            model_name='report',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='제보 위치 경도'),
        ),
        migrations.AddField(
            model_name='report',
            name='location_text',
            field=models.CharField(blank=True, help_text='예: 월계역 2번 출구 앞 건물 1층', max_length=200, verbose_name='위치 설명'),
        ),
        migrations.AddField(
            model_name='report',
            name='observed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='확인 시각'),
        ),
        migrations.RunPython(copy_created_at, migrations.RunPython.noop),
        migrations.AddField(
            model_name='report',
            name='profiles',
            field=models.JSONField(blank=True, default=list, help_text='제보자가 고른 이동 조건 키 목록. 예: ["WHEELCHAIR"]', verbose_name='이동 조건'),
        ),
        migrations.AddField(
            model_name='report',
            name='review_note',
            field=models.CharField(blank=True, help_text='충돌 항목 처리 방향 등 (처리 기록)', max_length=300, verbose_name='검토 의견'),
        ),
        migrations.AddField(
            model_name='report',
            name='suggested_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='새 장소 이름'),
        ),
        migrations.AlterField(
            model_name='report',
            name='note',
            field=models.CharField(blank=True, max_length=500, verbose_name='설명'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('building__isnull', True), ('entrance__isnull', True), ('place__isnull', False)), models.Q(('building__isnull', False), ('entrance__isnull', True), ('place__isnull', True)), models.Q(('building__isnull', True), ('entrance__isnull', False), ('place__isnull', True)), models.Q(('building__isnull', True), ('entrance__isnull', True), ('place__isnull', True), models.Q(('suggested_name', ''), _negated=True)), _connector='OR'), name='report_has_one_target_or_new_place'),
        ),
    ]
