# Generated by Django 5.2.17 on 2026-09-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_new_place_and_observed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='suggested_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='제안 주소'),
        ),
        migrations.AddField(
            model_name='report',
            name='suggested_category',
            field=models.CharField(blank=True, choices=[('RESTAURANT', '음식점'), ('CAFE', '카페'), ('STORE', '편의점·마트'), ('PHARMACY', '약국'), ('CLINIC', '병원·의원'), ('PUBLIC', '공공기관'), ('ETC', '기타')], max_length=20, verbose_name='제안 업종'),
        ),
        migrations.AddField(
            model_name='report',
            name='suggested_floor',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='제안 층'),
        ),
        migrations.AddField(
            model_name='report',
            name='suggested_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='제안 전화번호'),
        ),
    ]
