# Generated by Django 5.2.17 on 2026-09-30 16:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('reports', '0003_suggested_place_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='확인 시각')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconfirmations', to='places.place', verbose_name='장소')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconfirmations', to=settings.AUTH_USER_MODEL, verbose_name='확인한 사람')),
            ],
            options={
                'verbose_name': '지금도 맞아요',
                'verbose_name_plural': '지금도 맞아요',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['place', '-created_at'], name='reconfirm_place_recent')],
            },
        ),
    ]
