# Generated by Django 5.2.17 on 2026-10-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_reconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='source',
            field=models.CharField(choices=[('TEAM_SURVEY', '팀 답사'), ('USER_REPORT', '이용자 제보'), ('OWNER', '사장님·건물주'), ('AI', 'AI 판별'), ('PUBLIC_DATA', '공공데이터')], max_length=20, verbose_name='출처'),
        ),
    ]
