# Generated by Django 5.2.17 on 2026-10-01 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_fielddefinition_scope_accessfacility'),
        ('reports', '0005_public_data_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='report',
            name='report_has_one_target_or_new_place',
        ),
        migrations.AddField(
            model_name='report',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='places.accessfacility', verbose_name='접근 시설'),
        ),
        migrations.AddField(
            model_name='report',
            name='facility_kind',
            field=models.CharField(blank=True, choices=[('ENTRANCE', '출입구'), ('ELEVATOR', '엘리베이터 (E/V)'), ('ESCALATOR', '에스컬레이터 (E/S)'), ('STAIRS', '계단'), ('RAMP', '경사로'), ('TOILET', '장애인 화장실'), ('OTHER', '기타 접근 편의시설')], max_length=20, verbose_name='제안 시설 종류'),
        ),
        migrations.AddField(
            model_name='report',
            name='facility_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='제안 시설 이름'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('building__isnull', True), ('entrance__isnull', True), ('facility__isnull', True), ('place__isnull', False)), models.Q(('building__isnull', False), ('entrance__isnull', True), ('facility__isnull', True), ('place__isnull', True)), models.Q(('building__isnull', True), ('entrance__isnull', False), ('facility__isnull', True), ('place__isnull', True)), models.Q(('building__isnull', True), ('entrance__isnull', True), ('facility__isnull', False), ('place__isnull', True)), models.Q(('building__isnull', True), ('entrance__isnull', True), ('place__isnull', True), ('facility__isnull', True), models.Q(('suggested_name', ''), _negated=True)), _connector='OR'), name='report_has_one_target_or_new_place'),
        ),
    ]
