# Generated by Django 5.2.17 on 2026-10-04 12:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_remove_report_report_has_one_target_or_new_place_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PROCESSING', '분석 중'), ('SUCCEEDED', '완료'), ('FAILED', '실패')], default='PROCESSING', max_length=12, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='요청 시각')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 시각')),
                ('input_snapshot', models.JSONField(default=dict, verbose_name='분석 시점 입력')),
                ('field_definition_snapshot', models.JSONField(default=dict, verbose_name='분석 시점 항목 정의')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='검증한 결과')),
                ('error_code', models.CharField(blank=True, max_length=40, verbose_name='오류 코드')),
                ('error_message', models.CharField(blank=True, max_length=200, verbose_name='오류 안내')),
                ('model_id', models.CharField(blank=True, max_length=100, verbose_name='모델')),
                ('prompt_version', models.CharField(blank=True, max_length=50, verbose_name='지시문 버전')),
                ('schema_version', models.CharField(blank=True, max_length=50, verbose_name='출력 형식 버전')),
                ('provider_response_id', models.CharField(blank=True, max_length=100, verbose_name='OpenAI 응답 번호')),
                ('usage', models.JSONField(blank=True, null=True, verbose_name='토큰 사용량')),
                ('selection_history', models.JSONField(blank=True, default=list, verbose_name='운영자 선택 기록')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='reports.report', verbose_name='제보')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='요청한 운영자')),
            ],
            options={
                'verbose_name': 'AI 검토 보조 기록',
                'verbose_name_plural': 'AI 검토 보조 기록',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='ai_analysis_created')],
            },
        ),
    ]
