# Generated by Django 5.2.17 on 2026-10-04 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_aianalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ai_notice_version',
            field=models.CharField(blank=True, db_default='', default='', max_length=40, verbose_name='AI 안내 버전'),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_analyses', to='reports.report', verbose_name='제보'),
        ),
    ]
