# Generated by Django 5.2.17 on 2026-09-29 08:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionProfile',
            fields=[
                ('key', models.SlugField(help_text='예: WHEELCHAIR', max_length=30, primary_key=True, serialize=False, verbose_name='키')),
                ('label', models.CharField(max_length=30, verbose_name='이름')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='표시 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 중')),
            ],
            options={
                'verbose_name': '이동 조건',
                'verbose_name_plural': '이동 조건',
                'ordering': ['order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('ACCESSIBLE', '가능'), ('CONDITIONAL', '조건부'), ('DIFFICULT', '어려움')], max_length=12, verbose_name='결과')),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='작을수록 먼저 확인. 조건이 모두 맞는 첫 규칙의 결과를 씀', verbose_name='우선순위')),
                ('basis', models.CharField(choices=[('LAW', '법령'), ('APPLIED', '법령 준용'), ('TEAM', '팀 기준')], max_length=10, verbose_name='근거 구분')),
                ('note', models.CharField(blank=True, help_text='예: 편의증진법 시행규칙 별표 1 — 출입구 턱 2cm 이하', max_length=300, verbose_name='근거 설명')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='judgments.conditionprofile', verbose_name='이동 조건')),
            ],
            options={
                'verbose_name': '판정 규칙',
                'verbose_name_plural': '판정 규칙',
                'ordering': ['rule_set', 'profile', 'priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RuleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('LT', '<'), ('LTE', '≤'), ('GT', '>'), ('GTE', '≥'), ('EQ', '='), ('NE', '≠'), ('IS_TRUE', '예'), ('IS_FALSE', '아니오')], max_length=10, verbose_name='비교')),
                ('threshold', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='기준값')),
                ('threshold_text', models.CharField(blank=True, help_text='선택 필드 비교용. 예: 회전문', max_length=50, verbose_name='기준 글자')),
                ('ref_factor', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=6, verbose_name='기준 필드 배수')),
                ('if_missing', models.CharField(choices=[('UNKNOWN', '모름으로 처리 (정보가 없으면 미확인)'), ('FAIL', "조건 불충족으로 처리 (사장님 선언처럼 없으면 '없음'인 정보)")], default='UNKNOWN', max_length=10, verbose_name='값이 없을 때')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='places.fielddefinition', verbose_name='필드')),
                ('ref_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='places.fielddefinition', verbose_name='기준 필드')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='judgments.rule', verbose_name='규칙')),
            ],
            options={
                'verbose_name': '규칙 조건',
                'verbose_name_plural': '규칙 조건',
            },
        ),
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True, verbose_name='버전')),
                ('is_active', models.BooleanField(default=False, verbose_name='사용 중')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='변경 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '판정 규칙 버전',
                'verbose_name_plural': '판정 규칙 버전',
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='only_one_active_ruleset')],
            },
        ),
        migrations.AddField(
            model_name='rule',
            name='rule_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='judgments.ruleset', verbose_name='규칙 버전'),
        ),
        migrations.CreateModel(
            name='Judgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('ACCESSIBLE', '가능'), ('CONDITIONAL', '조건부'), ('DIFFICULT', '어려움'), ('UNKNOWN', '미확인')], max_length=12, verbose_name='결과')),
                ('reason', models.CharField(blank=True, help_text='예: 입구 단차 30cm · 계단 2칸', max_length=200, verbose_name='사실 한 줄')),
                ('rule_version', models.PositiveIntegerField(verbose_name='규칙 버전')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='계산 시각')),
                ('improved_at', models.DateTimeField(blank=True, null=True, verbose_name='개선 시각')),
                ('improved_to', models.CharField(blank=True, choices=[('ACCESSIBLE', '가능'), ('CONDITIONAL', '조건부'), ('DIFFICULT', '어려움'), ('UNKNOWN', '미확인')], max_length=12, verbose_name='개선 후 결과')),
                ('entrance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='places.entrance', verbose_name='판정 근거 출입구')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judgments', to='places.place', verbose_name='장소')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='judgments.conditionprofile', verbose_name='이동 조건')),
                ('matched_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='judgments.rule', verbose_name='적용 규칙')),
            ],
            options={
                'verbose_name': '판정 결과',
                'verbose_name_plural': '판정 결과',
                'constraints': [models.UniqueConstraint(fields=('place', 'profile'), name='one_judgment_per_place_profile')],
            },
        ),
    ]
