# Generated by Django 5.2.17 on 2026-09-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='stage',
            field=models.CharField(choices=[('ENTRANCE', '출입구'), ('FLOOR', '층 이동 (엘리베이터 등)')], default='ENTRANCE', max_length=10, verbose_name='적용 단계'),
        ),
    ]
